# Generated by Django 4.1.7 on 2023-04-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
